//! DATABASE_URL=... cargo test -p diraigent-api --test pagination_ordering -- --ignored
//! Use a disposable PostgreSQL database (sqlx creates an isolated test database).
use diraigent_api::{migration_runner, models::*, repository};
use sqlx::PgPool;
use uuid::Uuid;

async fn fixture(pool: &PgPool) -> (Uuid, Uuid) {
    migration_runner::run(pool).await.unwrap();
    let user = sqlx::query_scalar::<_, Uuid>(
        "INSERT INTO diraigent.auth_user (auth_user_id) VALUES ('pagination-test') RETURNING user_id",
    )
    .fetch_one(pool)
    .await
    .unwrap();
    let tenant = sqlx::query_scalar::<_, Uuid>(
        "INSERT INTO diraigent.tenant (name, slug) VALUES ('Test', 'pagination-test') RETURNING id",
    )
    .fetch_one(pool)
    .await
    .unwrap();
    let project = sqlx::query_scalar::<_, Uuid>(
        "INSERT INTO diraigent.project (name, slug, owner_id, tenant_id, package_id)
         VALUES ('Test', 'pagination-test', $1, $2,
                 (SELECT id FROM diraigent.package WHERE slug = 'software-dev')) RETURNING id",
    )
    .bind(user)
    .bind(tenant)
    .fetch_one(pool)
    .await
    .unwrap();
    (project, user)
}

// Fetch multiple small pages twice. Ties span both boundaries; exact IDs verify
// ordering and ensure no items are skipped or duplicated, including the last page.
macro_rules! assert_pages {
    ($pool:expr, $project:expr, $list:ident, $filters:ident, $expected:expr) => {
        for _ in 0..2 {
            let mut actual = Vec::new();
            for offset in [0, 2, 4, 6] {
                let rows = repository::$list(
                    $pool,
                    $project,
                    &$filters {
                        limit: Some(2),
                        offset: Some(offset),
                        ..Default::default()
                    },
                )
                .await
                .unwrap();
                actual.extend(rows.into_iter().map(|row| row.id));
            }
            assert_eq!(actual, $expected, "{}", stringify!($list));
        }
    };
}

#[sqlx::test(migrations = false)]
#[ignore = "requires disposable PostgreSQL DATABASE_URL"]
async fn timestamp_ties_have_stable_page_boundaries(pool: PgPool) {
    let (project, user) = fixture(&pool).await;
    // Deliberately insert in non-ID order so physical insertion order cannot
    // accidentally satisfy the contract. IDs 2..5 have identical timestamps.
    for n in [4, 1, 5, 3, 6, 2] {
        let id = Uuid::from_u128(n);
        let timestamp = match n {
            1 => "2026-01-01T00:00:00Z",
            6 => "2026-01-03T00:00:00Z",
            _ => "2026-01-02T00:00:00Z",
        };
        for (table, extra_columns, extra_values) in [
            ("task", "", ""),
            ("knowledge", ", content", ", 'Content'"),
            ("decision", ", context", ", 'Context'"),
            // The oldest work sorts first because sort_order takes precedence.
            (
                "work",
                ", sort_order",
                ", CASE WHEN $1 = '00000000-0000-0000-0000-000000000001'::uuid THEN -1 ELSE 0 END",
            ),
        ] {
            sqlx::query(&format!(
                "INSERT INTO diraigent.{table} (id, project_id, created_by, title, created_at{extra_columns})
                 VALUES ($1, $2, $3, 'Item', $4::text::timestamptz{extra_values})"
            ))
            .bind(id)
            .bind(project)
            .bind(user)
            .bind(timestamp)
            .execute(&pool)
            .await
            .unwrap();
        }
    }

    let expected: Vec<_> = [6, 2, 3, 4, 5, 1].map(Uuid::from_u128).into();
    assert_pages!(&pool, project, list_tasks, TaskFilters, expected);
    // Both spectator collections generated by the shared list_and_count macro.
    assert_pages!(&pool, project, list_knowledge, KnowledgeFilters, expected);
    assert_pages!(&pool, project, list_decisions, DecisionFilters, expected);
    let expected_work: Vec<_> = [1, 6, 2, 3, 4, 5].map(Uuid::from_u128).into();
    assert_pages!(&pool, project, list_works, WorkFilters, expected_work);
}
