-- Orchestra local SQLite schema.
-- All operational state for task execution lives here when orchestration_mode=local.

PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;

-- Task execution state (mirrors subset of API task table, orchestra-owned)
CREATE TABLE IF NOT EXISTS task_execution (
    task_id       TEXT PRIMARY KEY,
    project_id    TEXT NOT NULL,
    state         TEXT NOT NULL,
    playbook_id   TEXT,
    playbook_step INTEGER DEFAULT 0,
    assigned_agent_id TEXT,
    claimed_at    TEXT,
    completed_at  TEXT,
    state_entered_at TEXT,
    input_tokens  INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cost_usd      REAL    DEFAULT 0.0,
    last_synced_at TEXT,
    created_at    TEXT DEFAULT (datetime('now'))
);

-- Progress updates (progress, blocker, artifact, review, note)
CREATE TABLE IF NOT EXISTS task_update (
    id         TEXT PRIMARY KEY,
    task_id    TEXT NOT NULL,
    agent_id   TEXT,
    kind       TEXT NOT NULL,
    content    TEXT NOT NULL,
    metadata   TEXT DEFAULT '{}',
    synced     INTEGER DEFAULT 0,
    created_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_task_update_task ON task_update(task_id);
CREATE INDEX IF NOT EXISTS idx_task_update_unsynced ON task_update(synced) WHERE synced = 0;

-- Execution logs
CREATE TABLE IF NOT EXISTS task_log (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    task_id    TEXT NOT NULL,
    step_name  TEXT NOT NULL,
    content    TEXT NOT NULL,
    metadata   TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_task_log_task ON task_log(task_id);

-- Files changed during task execution
CREATE TABLE IF NOT EXISTS task_changed_file (
    id          TEXT PRIMARY KEY,
    task_id     TEXT NOT NULL,
    path        TEXT NOT NULL,
    change_type TEXT NOT NULL,
    diff        TEXT,
    synced      INTEGER DEFAULT 0,
    created_at  TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_changed_file_task ON task_changed_file(task_id);

-- File locks held by tasks
CREATE TABLE IF NOT EXISTS file_lock (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    task_id    TEXT NOT NULL,
    path_glob  TEXT NOT NULL,
    locked_by  TEXT NOT NULL,
    locked_at  TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_file_lock_project ON file_lock(project_id);
CREATE INDEX IF NOT EXISTS idx_file_lock_task ON file_lock(task_id);

-- Verification results
CREATE TABLE IF NOT EXISTS verification (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    task_id    TEXT,
    agent_id   TEXT,
    kind       TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'pass',
    title      TEXT NOT NULL,
    detail     TEXT,
    evidence   TEXT DEFAULT '{}',
    created_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_verification_task ON verification(task_id);

-- Events generated by orchestra
CREATE TABLE IF NOT EXISTS event (
    id              TEXT PRIMARY KEY,
    project_id      TEXT NOT NULL,
    kind            TEXT NOT NULL,
    source          TEXT NOT NULL DEFAULT 'orchestra',
    title           TEXT NOT NULL,
    severity        TEXT NOT NULL DEFAULT 'info',
    metadata        TEXT DEFAULT '{}',
    related_task_id TEXT,
    agent_id        TEXT,
    synced          INTEGER DEFAULT 0,
    created_at      TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_event_unsynced ON event(synced) WHERE synced = 0;
