use serde::{Deserialize, Serialize};

use crate::error::AppError;

/// A planned task generated by the AI from a work item's context.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlannedTask {
    pub title: String,
    pub kind: String,
    pub spec: String,
    pub acceptance_criteria: Vec<String>,
}

/// Tool input schema used with Claude's tool_use for structured output.
#[derive(Debug, Serialize)]
struct ToolInput {
    name: String,
    description: String,
    input_schema: serde_json::Value,
}

/// Anthropic Messages API request body.
#[derive(Debug, Serialize)]
struct AnthropicRequest {
    model: String,
    max_tokens: u32,
    tools: Vec<ToolInput>,
    tool_choice: serde_json::Value,
    messages: Vec<Message>,
}

#[derive(Debug, Serialize)]
struct Message {
    role: String,
    content: String,
}

/// Top-level response from Anthropic Messages API.
#[derive(Debug, Deserialize)]
struct AnthropicResponse {
    content: Vec<ContentBlock>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "type")]
enum ContentBlock {
    #[serde(rename = "tool_use")]
    ToolUse { input: ToolUseInput },
    #[serde(rename = "text")]
    #[allow(dead_code)]
    Text { text: String },
}

#[derive(Debug, Deserialize)]
struct ToolUseInput {
    tasks: Vec<PlannedTask>,
}

/// Call the Anthropic Claude API to generate a task plan from a work item.
pub async fn generate_task_plan(
    api_key: &str,
    title: &str,
    description: &str,
    success_criteria: &serde_json::Value,
    project_name: &str,
) -> Result<Vec<PlannedTask>, AppError> {
    let criteria_text = match success_criteria {
        serde_json::Value::Array(items) => items
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("- {s}")))
            .collect::<Vec<_>>()
            .join("\n"),
        serde_json::Value::String(s) => s.clone(),
        _ => success_criteria.to_string(),
    };

    let prompt = format!(
        r#"You are a technical project planner for the project "{project_name}".

Decompose the following work item into 3-8 concrete, implementable tasks. Each task should be small enough for a single developer to complete in one session.

## Work Item
**Title**: {title}
**Description**: {description}
**Success Criteria**:
{criteria_text}

## Requirements
- Order tasks by dependency (tasks that must be done first come first)
- Each task must have a clear, specific scope
- kind must be one of: feature, bug, refactor, test, docs
- spec should be a detailed technical description of what to implement
- acceptance_criteria should be verifiable conditions (not vague)
- Do NOT create meta-tasks like "review" or "deploy" — only implementation work"#,
        project_name = project_name,
        title = title,
        description = if description.is_empty() {
            "No description provided"
        } else {
            description
        },
        criteria_text = if criteria_text.is_empty() {
            "None specified".to_string()
        } else {
            criteria_text
        },
    );

    let tool = ToolInput {
        name: "create_task_plan".to_string(),
        description: "Create a plan of implementable tasks from a work item".to_string(),
        input_schema: serde_json::json!({
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "title": {
                                "type": "string",
                                "description": "Short, descriptive task title"
                            },
                            "kind": {
                                "type": "string",
                                "enum": ["feature", "bug", "refactor", "test", "docs"],
                                "description": "Type of task"
                            },
                            "spec": {
                                "type": "string",
                                "description": "Detailed technical specification of what to implement"
                            },
                            "acceptance_criteria": {
                                "type": "array",
                                "items": { "type": "string" },
                                "description": "List of verifiable conditions that must be met"
                            }
                        },
                        "required": ["title", "kind", "spec", "acceptance_criteria"]
                    },
                    "minItems": 3,
                    "maxItems": 8
                }
            },
            "required": ["tasks"]
        }),
    };

    let request = AnthropicRequest {
        model: "claude-sonnet-4-20250514".to_string(),
        max_tokens: 4096,
        tools: vec![tool],
        tool_choice: serde_json::json!({"type": "tool", "name": "create_task_plan"}),
        messages: vec![Message {
            role: "user".to_string(),
            content: prompt,
        }],
    };

    let client = reqwest::Client::new();
    let response = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .header("content-type", "application/json")
        .json(&request)
        .send()
        .await
        .map_err(|e| {
            tracing::error!(error = %e, "Failed to call Anthropic API");
            AppError::Internal(format!("Failed to call AI service: {e}"))
        })?;

    let status = response.status();
    if !status.is_success() {
        let body = response.text().await.unwrap_or_default();
        tracing::error!(status = %status, body = %body, "Anthropic API returned error");
        return Err(AppError::Internal(format!(
            "AI service returned {status}: {body}"
        )));
    }

    let api_response: AnthropicResponse = response.json().await.map_err(|e| {
        tracing::error!(error = %e, "Failed to parse Anthropic API response");
        AppError::Internal(format!("Failed to parse AI response: {e}"))
    })?;

    // Extract the tool_use content block
    for block in api_response.content {
        if let ContentBlock::ToolUse { input } = block {
            return Ok(input.tasks);
        }
    }

    tracing::error!("Anthropic API response contained no tool_use block");
    Err(AppError::Internal(
        "AI response did not contain expected structured output".into(),
    ))
}
